// SPDX-License-Identifier: UNLICENSED
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.8.0. SEE SOURCE BELOW. !!
pragma solidity >=0.7.0 <0.9.0;

interface IReaperVaultV2 {
    function balanceOf(address owner) external view returns (uint256);

    function redeem(uint256 shares, address receiver, address owner) external returns (uint256 assets);
}
